<?php

namespace Container9fBmif4;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_DyXehMnService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.dyXehMn' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.dyXehMn'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'bankRepository' => ['privates', 'App\\Repository\\BankRepository', 'getBankRepositoryService', true],
            'userRepository' => ['privates', 'App\\Repository\\UserRepository', 'getUserRepositoryService', true],
        ], [
            'bankRepository' => 'App\\Repository\\BankRepository',
            'userRepository' => 'App\\Repository\\UserRepository',
        ]);
    }
}
