<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerYQVibLF\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerYQVibLF/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerYQVibLF.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerYQVibLF\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerYQVibLF\App_KernelDevDebugContainer([
    'container.build_hash' => 'YQVibLF',
    'container.build_id' => 'e603c530',
    'container.build_time' => 1680858300,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerYQVibLF');
