<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container42Gdoyh\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container42Gdoyh/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container42Gdoyh.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container42Gdoyh\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container42Gdoyh\App_KernelDevDebugContainer([
    'container.build_hash' => '42Gdoyh',
    'container.build_id' => 'c7492aaf',
    'container.build_time' => 1680778199,
], __DIR__.\DIRECTORY_SEPARATOR.'Container42Gdoyh');
